W=input('digite alguma palavra')
print('O seu tipo primitivo é {}'.format(type(W)))
print('Apenas espaços?',W.isspace())
print('É apenas numeros?',W.isnumeric())
print('É alfabetico?',W.isalpha())
print('É alfanumerico?',W.isalnum())
print('É maiusculo?',W.isupper())
print('É minusculo?',W.islower())
print('É capitaliado?',W.iscapitalize())
